### ISSUE TITLE
Not connecting to MQTT

### ISSUE THREAD

**Issue by johannesmichael** [SoftwareAG/cumulocity-xdk-agent#1]
Hi, I tried the XDK Agent, registration was successful, but now I am getting this:

XDK DEVICE 1: MQTTOperation: Successfully connected to [mqtt.eu-latest.cumulocity.com:8883]
 INFO | XDK DEVICE 1: MQTTOperation: Start publishing ...
 INFO | XDK DEVICE 1: MQTTOperation: Reading boot status: [0]
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 50,,Error of type: MeasurementManagementServiceException with message: Invalid value for source argument!
 INFO | XDK DEVICE 1: MQTTOperation: Error from upstream: s/e, Error Msg : 41,,Template ids '99
 INFO | XDK DEVICE 1:         17 [EXH:2] M=0x0F, E=0x02, S=0x2 (0x0F82)
 INFO | XDK DEVICE 1:         17 [EXH:2] M=0x0F, E=0x01, S=0x2 (0x0F81)
 INFO | XDK DEVICE 1: Error in ServalPAL package.
 INFO | XDK DEVICE 1: 	Package ID: 30
 INFO | XDK DEVICE 1: 	Module ID: 8
 INFO | XDK DEVICE 1: 	Severity code: 2
 INFO | XDK DEVICE 1: 	Error code: 1
 INFO | XDK DEVICE 1: MQTT_ConnectToBroker_Z: Failed since Connect event was not received 
 INFO | XDK DEVICE 1: MQTTOperation: MQTT connection to the broker failed, try again : [1] ... 
 INFO | XDK DEVICE 1: MQTT_ConnectToBroker_Z: Failed since Connect event was not received 
 INFO | XDK DEVICE 1: MQTTOperation: MQTT connection to the broker failed, try again : [2] ... 
 INFO | XDK DEVICE 1: timezoneISO8601format - 2021-07-04T15:09:23Z
 INFO | XDK DEVICE 1: MQTTOperation: MQTT publish failed 
 INFO | XDK DEVICE 1: Error in XDK110 Application package.
 INFO | XDK DEVICE 1: 	Package ID: 153
 INFO | XDK DEVICE 1: 	Module ID: 39
 INFO | XDK DEVICE 1: 	Severity code: 2
 INFO | XDK DEVICE 1: 	Error code: 136
 INFO | XDK DEVICE 1: timezoneISO8601format - 2021-07-04T15:10:24Z

I am using a eu-latest tenant for testing. Workbench 3.6.1.
And I do not see my device.
And no credentials are added to my SD Card.

Any suggestions?

**Comment by ck-c8y** [comment]
Hi johannesmichael,

the issue was related to missing permissions for the role "device" in your tenant. The role "device" could not create devices.
As a result the device could not be created and this resulted in the error message " Invalid value for source argument!"
